parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: symf
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: b9805b95728c4ff8f8f4f719110c5ddd9
    database_path: null
